server/player/events.lua, server/player/main.lua
* Found this issue with Entered and Left scope events where getting the inScope table was failing to self.source being nil
* While investigating that issue, I also realized that playerData never got removed after a player logged out or left the server
* While figuring out where to nil out playerData entries, I realized that the ox:playerLogout event trigger was attempting to get values from an incorrect object
=> fix: Player getters getting called correctly for player scope changes

server/vehicle/main.lua
This native was introduced as a complete native instead of one that has to be invoked, so we can use that instead
=> tweak(server/vehicle/main): use native instead of invoking

fxmanifest.lua
* With the usage of the CreateVehicleServerSetter native call a server version bump is required
=> chore(manifest): Bump server dependency version

server/player/class.lua
On logout, a player was losing their inScope table. This update wipes the table but keeps it around
=> fix(server/player): Wipe inScope table on logout

server/player/events.lua
inService should also be available on the client side. For example, when listing all my groups to indicate the group in which I am inService. Not sure if its the best to replicate the value or set a statebag and hook a statebag change.
=> inService accessable on a clientside

client/spawn.lua
Player Ped was loading on some clients before collisions. Tested on a few potato PCs, unable reproduce initial bug after changes.
=> Fix falling at spawn

database.sql
This affected MariaDB 10.10.2 unsure if it also causes issues with other versions or not.
=> fixed syntax error caused by extra space

client/spawn.lua
I do not have currently an option to make a video of it so lemme quickly describe it
1. Select already created character that has a tattos (otherwise create a new character, apply tattos and logout back to character selection)
2. Make sure your character is selected and ped is visible
3. Create a new character
4. Your character will have a tattos of a character that you have had selected before you started creating a new character, or you can select random tattoos during a character creation in fivem-appearance and those tattos will appears also
This does not happen when you have not selected other character before you create a new character
I hope it makes sense, if not I will make a video later
=> fix (ox_core/client): Duplicating tattoos from character to character

server/player/events.lua
* Since moving the `player:set` calls after the `ox:loadPlayer` event player doesn't have the gender field set yet, so we should use cData.gender instead
=> fix(server/player): Use existing gender information

server/player/class.lua
Almost nothing but it triggered me lol
The type of `filter` is defined as `string | string[] | table<string, number> }`.
It seems there's an extra closing curly brace `}` at the end that seems to be a typo.
=> fix(server/player/class): param type extra closing curly brace

server/player/events.lua
Get correct data for `isDead` stored in DB.
=> fix(server/db): sync health on player spawn

server/vehicle/class.ts
The actual method `+Date() / 1000` return Not a number so it's generate VIN with this format `9OXSU2VNaN`
=> fix(vehicle): change method to get date seconds in vin generation

server/accounts/db.ts
If column is group, it will throw a syntax error, so we need to prevent this
=> fix(server/account): prevent sql syntax error if column is group

lib/client/player.lua
If you spawn at the first time, metadata can't be call, `__call method does not exist`
=> fix(lib/player): get metadata at first spawn

locales/en.json, server/accounts/db.ts, server/accounts/index.ts, sql/install.sql
This PR implements basics transactions logs in db to retrieves transactions in ox_banking https://github.com/overextended/ox_banking/pull/7
Ex :
`exports.ox_core:AddAccountBalance(account.id, 450, "Salary")`
`exports.ox_core:RemoveAccountBalance(account.id, 350000, false, "Premium Deluxe Motorsport")`
=> feat(accounts/transactions): add transactions stuff

sql/install.sql
This PR fix/resolves following:
- Tabs
- Unification of keys and column types
- Added missing constraints
- onTick was increased because with current value you are limited to 166 minutes from 0 to 100 and its to short for some statuses e.g. addictions
**No column or table name has been changed**
=> fix(sql/install): unification, keys, formatting

client/player/status.ts
This PR fixes following:
After https://github.com/overextended/ox_core/commit/4e7a126bc8bee392efd3ac040093d80e7cbd151b onTick change, value was rounded to only 4 decimals instead of 8
=> fix(client/player): round status value to 8 decimals

client/vehicle/parser.ts
Fixes an error when parsing only _new_ vehicles (`parseAll` set to false).
The function would throw error when requesting the undefined vehicle model.
It should instead skip this vehicle since it already exists - which is done by filtering the values.
=> fix(client/vehicle): filter undefined values in vehicle parser

locales/en.json, server/accounts/db.ts, server/accounts/index.ts, server/config.ts, server/player/events.ts, sql/install.sql
This PR improves accounts with following changes:
1. Account Ids are no longer boring auto increments but are randomly generated to improve feeling
2. Added *createDefaultAccount* Convar in case default accounts are not desired
3. Added optional *note* column to transactions for a sake of having a way to have custom notes
4. Improved return values for better integration of accounts to 3rd party resources
Tested with:
```lua
RegisterCommand('createAccount', function(playerId, args)
local OxPlayer = Ox.GetPlayer(playerId)
if not OxPlayer or not OxPlayer.charId then return end
local retval = Ox.CreateAccount(OxPlayer.charId, args[1])
print(retval)
end)
RegisterCommand('transferBalance', function(playerId, args)
local OxPlayer = Ox.GetPlayer(playerId)
if not OxPlayer or not OxPlayer.charId …
```
=> feat(accounts): accounts Id, from/toBalance, notes and return values

sql/install.sql
This PR fixes an error when importing the SQL file. 
'ox_group_grades' table should be created after 'account_roles' table because it's a foreign key.
=> fix(sql): create ox_group_grades table after account_roles

server/player/db.ts
Fixes an issue where new user is created every time player without license2 connects.
=> fix(server/player): add license fallback

server/vehicle/index.ts
Fixes an issue introduced in https://github.com/overextended/ox_core/commit/518b4674e0ab6c0d3f5a502cf883cd608f118c54 where `CreateVehicle` fails to insert vehicle data to the database when creating new vehicle due to plate being undefined.
=> fix(server/vehicle):  add undefined plate check

sql/install.sql
Fixes SQL syntax error during installation.
=> fix(sql): Missing comma in ox_groups table creation

server/accounts/db.ts
When removing money using `account.removeBalance()` ox_banking transaction log shows the balance as if it was added. 
[ox_banking uses from balance as newBalance](https://github.com/overextended/ox_banking/blob/main/src/server/index.ts#L534), so we are now updating the balance by taking away the amount if addAction is not "add".
=> fix(server/accounts): transaction new balance

server/vehicle/class.ts
This commit adds a `getProperties` method, allowing vehicle properties to be retrieved, which was not possible before.
=> feat(server/vehicle): add getProperties method

server/player/class.ts
This PR fixes an issue where removing active group from player didn't properly update the `group:activeCount` GlobalState due to `activeGroup` being removed earlier that calling `removeGroup` method (which contains the GlobalState update).
=> fix(server/player): remove group before removing active group

server/player/class.ts
When a player disconnects/logs out while having an `activeGroup` the `groupName:activeCount` was getting decremented correctly, but when connecting afterwards it misses an increment due to it checking for `activeGroup` and attempting to increment before `activeGroup` gets set in the log in process.
This seems to fix it.
=> fix(server/player/class): Incriment active group count in correct order

server/vehicle/class.ts
Currently, when calling `vehicle.respawn(...)` if the entity of the vehicle currently exists, it will attempt to delete the vehicle from the database rather than delete the entity.
=> fix(server/vehicle) Delete vehicle entity on respawn, not delete from DB

server/accounts/db.ts
Return `no_balance` instead of `something_went_wrong` in `UpdateBalance` when the account doesn’t have enough balance.
=> fix(server/accounts): return 'insufficient_balance' if not enough balance

server/accounts/db.ts
Documentation states that the transaction (remove / add / transfer) message parameter is optional. However, this isn't always going to work, since, on transaction, a new row is added into `accounts_transactions`. If the message isn't specified in an `OxAccount` function, let's say, `removeBalance` it's going to spit out an error specifying so, because the SQL does not allow the said column to be NULL.
Hence, if the documentation is indeed correct and it's not required to specify a message (reason), then the proposed changes should apply the default withdrawal / deposit locales if `message` does not exist.
=> fix(server/account): missing transaction reason causing db errors

lib/server/index.ts, server/player/db.ts, server/player/license.ts, types/index.ts
Implements a way using the core functions to get license data instead of having to write own queries.
```lua
RegisterCommand('test', function(source)
local player = Ox.GetPlayer(source)
lib.print.info(Ox.GetLicenses(), Ox.GetLicense('driver'), player.getLicense(), player.getLicense('driver'))
end)
```
I will pr docs when accepted for merge.
=> feat(server/player): GetLicense and GetLicenses exports

server/accounts/db.ts, server/vehicle/index.ts
This PR aims to add the vehicle properties to the vehicle's metadata, which will get added to the database, on creation.
=> fix(server/vehicle): send vehicle properties on db creation

server/player/loading.ts
Mainly done  in this changes : 
> Added player variable declaration outside try block for proper scope
> Added cleanup in catch block to prevent orphaned player instances
> Maintained all existing return values and error messages
> Added nested try-catch for cleanup operations
> Kept all property assignments within main try block
> Added proper error logging for both main error and cleanup errors
1 > Fix the build issue.
2 > Maintain all existing functionality.
3 > Prevent memory leaks.
4 > Provide better error handling.
5 > Keep all existing interfaces intact.
=> fix(server/player): handle player loading errors and cleanup

build.js
Building to ES2023 does not allow the client to join the server. After testing, reverting the target back to ES2021 has successfully fixed it.
=> fix: revert client build target to ES2021

server/player/class.ts
This PR fixes an issue where `group:activeCount` wouldn't increase back after changing grade while keeping the same group.
Issue reproduction steps:
1. `/setgroup me police 1`
2. set `police` as active group
3. check `police:activeCount` (1)
4. `/setgroup me police 2`
5. check `police:activeCount` (0)
=> fix(server/player): increase activeCount back when changing grade

lib/server/vehicle.lua
Using Ox.GetVehicleFromEntity in a callback with a wait would randomly crash my server thought it was Node 22 related but once I added it to the lib it worked 🤷
=> Chore: add GetVehicleFromEntity to lib

server/groups/index.ts
Hi there,
I noticed that the setgroup command does not appear to have any permission checks, such as restricted: group.admin or something similar.
If I'm understanding the current implementation correctly, this would mean that any user can execute the command and assign themselves to any group, including admin-level groups. This could potentially lead to serious security and access control issues.
Could you confirm whether this is intended behavior or an oversight?
In this PR, I’ve added a restriction requiring the group.admin permission.
Thanks in advance!
=> fix(server/groups): add restriction to setgroup command

server/vehicle/class.ts
Basically this.despawn does not trigger `OxVehicle.remove(this.vin)` and if we delete an entity without removing it from OxVehicle it tries to respawn it using the old entity and it breaks.
This just changes this,despawn to this.remove which does the same but also calls `OxVehicle.remove(this.vin)` not sure if it should of been just called directly in despawn, not sure as I couldnt see any use cases for that but I just went the "safe route"
=> fix(setStored): remove vin from OxVehicle list
