database.sql
Reorganize importing procedure to fix this error when importing database.sql
=> fix(sql): foreign key error when importing

.editorconfig, database.sql, server/player/class.lua, server/player/db.lua, server/player/main.lua
~~this is not tested~~
this is tested
=> feat: save metadata

client/spawn.lua, server/player/main.lua
tested
average fivem player not smart enough to change model to `mp_f_freemode_01` when selecting female in character creation
=> feat: set ped model from gender

imports/server/vehicle.lua
=> Vehicle exports fix

database.sql, server/vehicle/class.lua, server/vehicle/db.lua, server/vehicle/main.lua
=> feat(server/vehicle): group vehicles

database.sql
Fix a typo I made did say the pr was untested smh
=> Fix(sql): typo

locales/cs.json
=> Update cs.json locales

client/death.lua
Pr: https://github.com/overextended/ox_lib/commit/cfb3e4c7d96c1b59d7f8240119f8f77b1da45a03
=> refactor(client/death): use new lib.requestScaleformMovie function

web/src/layouts/characters/components/CreateCharacter.tsx
with help from luke this seems to be a solution to being unable to create a character
=> Fix for create character bug

locales/zh-cn.json, locales/zh-tw.json
Update Chinese Simplified and Chinese Traditional language files.
=> Update Chinese Simplified and Chinese Traditional language files

client/death.lua
The wasted scaleform wasn't showing.
=> fix(client/death): get scaleform handle

client/events.lua, server/vehicle/main.lua
* The terminating clause was lost on the conversion to the state bag change handler helper function
* Fixed up / updated some error logging in CreateVehicle
=> fix(vehicle): Prevent infinite loop on vehicle spawn init

locales/de.json
=> Add German locales

server/vehicle/main.lua, server/vehicle/registry.lua
=> Check if entity exist

client/player/death.ts, server/player/class.ts
This PR is resolving issues with death system, typo and sync with server for saving current death state in db
=> fix(death): some changes about death state

lib/client/player.lua, lib/client/player.ts
=> fix(lib): update groups on player loaded

client/player/index.ts, server/player/class.ts
It follow this PR https://github.com/overextended/ox_core/pull/126
We have forgot to update the setStatus and client side
Also, we change the hasOwnProperty to use a better performance way
https://jsperf.app/wifiqi/5
Marked this as draft because i have to test it
=> fix(player/status): optimize and uniformization of status check

client/vehicle/index.ts
Since https://github.com/citizenfx/fivem/issues/2425 has been resolved, we need to get rid of this hacky solution and cleanup
=> fix(client/vehicle): remove init tweak ped remover

pnpm-lock.yaml, server/vehicle/class.ts
Value of `owner` column should be the `charId`, not `group`.
I've also updated the pnpm lockfile version, since `6.0` is outdated.
=> fix(server/vehicle): use correct value when setting owner column

server/vehicle/class.ts
This is needed to get the value of stored for garages
=> feat(server/vehicle): Change stored to public field

locales/cs.json
This PR adds Czech (cs) locales.
=> feat(locales): cs translation

locales/zh-cn.json, locales/zh-tw.json
Add Chinese Simplified and Traditional translations
=> feat(locales): zhcn and zhtw translation

locales/nl.json
=> feat(locales): nl translation

locales/jp.json
=> feat(locales): jp translation

locales/sk.json
This PR adds Slovak (sk) translations
=> feat(locales): sk translation

locales/de.json
=> feat(locales): de translation

server/vehicle/index.ts
Fixed an issue where properties were not loading from the database.
=> fix(server/vehicle): Load database properties

server/groups/index.ts
push method return the new length of the array
=> fix(server/groups): update globalstate properly

server/bridge/ox_inventory.ts
- should be `dateOfBirth` as stated in database shema
=> fix(server/bridge): dob naming

server/vehicle/index.ts
Should solve the issue that was reported a few days ago. All that is changed is to check whether coords exist before returning if the entity does not.
=> fix(server/vehicle): vehicle not saving to db if no coords passed (#208)

server/vehicle/class.ts
Useful in cases where you need to do something with a vehicle before it gets despawned. Will make pr for docs if this gets accepted.
=> feat(server/vehicle): ox:despawnVehicle event

server/accounts/db.ts
Events when transactions are done. Similar concept to the ``ox:invoicePaid`` event. I personally use these to notify players on their phone when these actions happen.
If merged, I will pr docs.
=> feat(server/accounts): transaction events

locales/de.json
once again updating them to keep track of this project :3
=> update (locales/de): grammar fixes and updating

locales/es.json
This PR updates the Spanish locale file to align with the latest additions in the localization system.
=> update (locales/es): missing locales

locales/fr.json
i update the french locale after the _implement ban system_ [a5d2994](https://github.com/overextended/ox_core/commit/a5d299482c0953ec2190d86ad5dc08d71c1fac70) update
=> update french locales
